docs(web): updated `maplibre-gl` JavaScript and CSS version to `5.24.0` in `README.md` (#814)
In `README.md` web section the JavaScript and CSS `maplibre-gl` version
is `4.3.0`.

Configuring web project using old version `4.3.0` causes
`NoSuchMethodError: tried to call a non-function, such as null:
'this.jsObject.unsubscribe'` on `MapLibreMap` dispose as reported in
#808.

Upgrading to `5.24.0` exception isn't raised.